logging:
  version: 1
  loggers:
    xknx.raw_socket:
      level: INFO
  root:
    handlers:
      - stderr
    level: INFO
  handlers:
    stderr:
      class: logging.StreamHandler
      level: DEBUG
      formatter: std
      stream: "ext://sys.stderr"
  formatters:
    std:
      class: moat.util.TimeOnlyFormatter
      format: "%(asctime)s %(levelname)s:%(name)s:%(message)s"
  disable_existing_loggers: false
